version: "3.8"

networks:
    items:
        external: true
        name: db_items-network
    common:
        external: true
        name: internal-network

services:
    # item
    item:
        image: item-service:0.0.1-SNAPSHOT
        env_file: ~/docker/container_configs/item/.env
        networks:
            - items
            - common
        ports:
            - 8443:8443
