package com.cnewbywa.item.model;

import java.util.UUID;

import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Version;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

@Entity
@Getter
@SuperBuilder
@NoArgsConstructor
public class Item extends Audit {

	public Item(String name, String description) {
		this.name = name;
		this.description = description;
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	@Column(name = "item_id")
	@Generated(event = EventType.INSERT) // using a Hibernate annotation to get value generated by db
	private UUID itemId;
	@Size(min = 3, max = 50)
	@NotBlank
	@Setter
	private String name;
	@Size(min = 3, max = 500)
	@NotBlank
	@Setter
	private String description;
	@Version
	private long version;
}
